
INSERT INTO PUBLIC.RESIDENT (TYPE, RESIDENCE_ID, NAME, SURNAME) VALUES(1, NULL, 'Thiago', 'Cunha');
INSERT INTO PUBLIC.RESIDENT (TYPE, RESIDENCE_ID, NAME, SURNAME) VALUES(1, NULL,  'Daniel', 'Figueredo');
INSERT INTO PUBLIC.RESIDENT (TYPE, RESIDENCE_ID, NAME, SURNAME) VALUES(0, NULL, 'Vitor', 'Lana');
INSERT INTO PUBLIC.RESIDENT (TYPE, RESIDENCE_ID, NAME, SURNAME) VALUES(0, NULL, 'Alex', 'Granato');
INSERT INTO PUBLIC.RESIDENT (TYPE, RESIDENCE_ID, NAME, SURNAME) VALUES(0, NULL, 'Alan', 'Cavalini' );
INSERT INTO PUBLIC.RESIDENT (TYPE, RESIDENCE_ID, NAME, SURNAME) VALUES (0, NULL, 'Fernando', 'Cavalini');



INSERT INTO PUBLIC.RESIDENCE (ID, AREA, IDEAL_FRACTION, TYPE, NUMBER, RESIDENT_NAME) VALUES( (SELECT UUID()),50, 0.1724 , 0,  2311, 'Alex');
INSERT INTO PUBLIC.RESIDENCE (ID, AREA, IDEAL_FRACTION, TYPE, NUMBER, RESIDENT_NAME) VALUES( (SELECT UUID()),70, 0.2414 , 1,  2222, 'Thiago');
INSERT INTO PUBLIC.RESIDENCE (ID, AREA, IDEAL_FRACTION, TYPE, NUMBER, RESIDENT_NAME) VALUES( (SELECT UUID()),35, 0.1207 , 1,  2331, 'Daniel');
INSERT INTO PUBLIC.RESIDENCE (ID, AREA, IDEAL_FRACTION, TYPE, NUMBER, RESIDENT_NAME) VALUES( (SELECT UUID()),55, 0.1897 , 0,  2424, 'Vitor');
INSERT INTO PUBLIC.RESIDENCE (ID, AREA, IDEAL_FRACTION, TYPE, NUMBER, RESIDENT_NAME) VALUES( (SELECT UUID()),80, 0.2759 , 0,  3123, 'Alan');
INSERT INTO PUBLIC.RESIDENCE (ID, AREA, IDEAL_FRACTION, TYPE, NUMBER, RESIDENT_NAME) VALUES( (SELECT UUID()),100.00, 1.0000000000, 0, 2222, 'Fernando');



UPDATE PUBLIC.RESIDENT SET RESIDENCE_ID=(SELECT ID FROM RESIDENCE WHERE RESIDENT_NAME = 'Daniel')   WHERE NAME='Daniel' AND SURNAME='Figueredo';
UPDATE PUBLIC.RESIDENT SET RESIDENCE_ID=(SELECT ID FROM RESIDENCE WHERE RESIDENT_NAME = 'Alex')     WHERE NAME='Alex' AND SURNAME='Granato';
UPDATE PUBLIC.RESIDENT SET RESIDENCE_ID=(SELECT ID FROM RESIDENCE WHERE RESIDENT_NAME = 'Alan')     WHERE NAME='Alan' AND SURNAME='Cavalini';
UPDATE PUBLIC.RESIDENT SET RESIDENCE_ID=(SELECT ID FROM RESIDENCE WHERE RESIDENT_NAME = 'Thiago')   WHERE NAME='Thiago' AND SURNAME='Cunha';
UPDATE PUBLIC.RESIDENT SET RESIDENCE_ID=(SELECT ID FROM RESIDENCE WHERE RESIDENT_NAME = 'Vitor')    WHERE NAME='Vitor' AND SURNAME='Lana';
UPDATE PUBLIC.RESIDENT SET RESIDENCE_ID=(SELECT ID FROM RESIDENCE WHERE RESIDENT_NAME = 'Fernando')   WHERE NAME='Fernando' AND SURNAME='Cavalini';



INSERT INTO PUBLIC.CONDOMINIUM (EXPENSES, TOTAL_AREA, ADDRESS, NAME) VALUES (7654,290, 'SAN PEDRO VALLEY','BELORYHILLS');
INSERT INTO PUBLIC.CONDOMINIUM (EXPENSES, TOTAL_AREA, ADDRESS, NAME) VALUES (714.61, 100.00, 'Count of the punpkins', 'Count');


INSERT INTO PUBLIC.CONDOMINIUM_RESIDENCES (RESIDENCES_ID, CONDOMINIUM_ADDRESS, CONDOMINIUM_NAME) VALUES ((SELECT ID FROM RESIDENCE WHERE RESIDENT_NAME = 'Daniel'), 'Count of the punpkins', 'Count');
INSERT INTO PUBLIC.CONDOMINIUM_RESIDENCES (RESIDENCES_ID, CONDOMINIUM_ADDRESS, CONDOMINIUM_NAME) VALUES ((SELECT ID FROM RESIDENCE WHERE RESIDENT_NAME = 'Alex')  , 'SAN PEDRO VALLEY', 'BELORYHILLS');
INSERT INTO PUBLIC.CONDOMINIUM_RESIDENCES (RESIDENCES_ID, CONDOMINIUM_ADDRESS, CONDOMINIUM_NAME) VALUES ((SELECT ID FROM RESIDENCE WHERE RESIDENT_NAME = 'Alan')  , 'SAN PEDRO VALLEY', 'BELORYHILLS');
INSERT INTO PUBLIC.CONDOMINIUM_RESIDENCES (RESIDENCES_ID, CONDOMINIUM_ADDRESS, CONDOMINIUM_NAME) VALUES ((SELECT ID FROM RESIDENCE WHERE RESIDENT_NAME = 'Thiago'), 'SAN PEDRO VALLEY', 'BELORYHILLS');
INSERT INTO PUBLIC.CONDOMINIUM_RESIDENCES (RESIDENCES_ID, CONDOMINIUM_ADDRESS, CONDOMINIUM_NAME) VALUES ((SELECT ID FROM RESIDENCE WHERE RESIDENT_NAME = 'Vitor') , 'SAN PEDRO VALLEY', 'BELORYHILLS');
INSERT INTO PUBLIC.CONDOMINIUM_RESIDENCES (RESIDENCES_ID, CONDOMINIUM_ADDRESS, CONDOMINIUM_NAME) VALUES ((SELECT ID FROM RESIDENCE WHERE RESIDENT_NAME = 'Fernando'), 'SAN PEDRO VALLEY', 'BELORYHILLS');

